### ISSUE TITLE
 witeness of the output circuit.circom file  generation failed

### ISSUE THREAD

**Issue by zjingwang** [socathie/keras2circom#3]
Hi, i am a new learner in zkml and i am using this keras2circom with **_dokcer python3.9.16_**, and i got this problem,
when i tried to generate witness with the output **_circuit.circom and circuit.json_**, **_i had this error:_**

`~/Desktop/PrivacyComputing/proof-of-sql/practices/keras2circom/output]$ node circuit_js/generate_witness.js circuit_js/circuit.wasm  circuit.json circuit.wtns
/Desktop/PrivacyComputing/proof-of-sql/practices/keras2circom/output/circuit_js/witness_calculator.js:167
            throw new Error(`Not all inputs have been set. Only ${input_counter} out of ${this.instance.exports.getInputSize()}`);
                  ^
Error: Not all inputs have been set. Only 674 out of 1458
    at WitnessCalculator._doCalculateWitness (/Desktop/PrivacyComputing/proof-of-sql/practices/keras2circom/output/circuit_js/witness_calculator.js:167:12)
    at WitnessCalculator.calculateWTNSBin (/Desktop/PrivacyComputing/proof-of-sql/practices/keras2circom/output/circuit_js/witness_calculator.js:212:20)
    at /Desktop/PrivacyComputing/proof-of-sql/practices/keras2circom/output/circuit_js/generate_witness.js:15:38
`

and **here are the logs when i generated the circom file:**

`root@d4a5c9f0cdc9:/usr/wzj# python main.py models/alt_model.h5 
2023-04-11 02:38:43.782470: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-11 02:38:44.014700: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-11 02:38:44.023624: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-04-11 02:38:44.023696: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-04-11 02:38:44.064497: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-04-11 02:38:45.111990: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-04-11 02:38:45.112222: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-04-11 02:38:45.112262: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-04-11 02:38:46.222013: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-04-11 02:38:46.222106: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2023-04-11 02:38:46.222317: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (d4a5c9f0cdc9): /proc/driver/nvidia/version does not exist
2023-04-11 02:38:46.222715: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
`

am i using keras2circom wrong? looking forward to your anser, thank you.

**Comment by socathie** [comment]
The circuit.json only sets the model weights, you would need to set your input signals separately.

**Comment by zjingwang** [comment]
i just found that, than you sir.
